//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Music.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.spotifydupauvremobile.ui.transform.MusicIce;

public interface MusicPrx extends com.zeroc.Ice.ObjectPrx
{
    default boolean ajoutMusique(String titre, String auteur, String fichierAudio)
    {
        return ajoutMusique(titre, auteur, fichierAudio, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean ajoutMusique(String titre, String auteur, String fichierAudio, java.util.Map<String, String> context)
    {
        return _iceI_ajoutMusiqueAsync(titre, auteur, fichierAudio, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> ajoutMusiqueAsync(String titre, String auteur, String fichierAudio)
    {
        return _iceI_ajoutMusiqueAsync(titre, auteur, fichierAudio, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> ajoutMusiqueAsync(String titre, String auteur, String fichierAudio, java.util.Map<String, String> context)
    {
        return _iceI_ajoutMusiqueAsync(titre, auteur, fichierAudio, context, false);
    }

    /**
     * @hidden
     * @param iceP_titre -
     * @param iceP_auteur -
     * @param iceP_fichierAudio -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_ajoutMusiqueAsync(String iceP_titre, String iceP_auteur, String iceP_fichierAudio, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "ajoutMusique", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_titre);
                     ostr.writeString(iceP_auteur);
                     ostr.writeString(iceP_fichierAudio);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean supprimerMusique(String titre)
    {
        return supprimerMusique(titre, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean supprimerMusique(String titre, java.util.Map<String, String> context)
    {
        return _iceI_supprimerMusiqueAsync(titre, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> supprimerMusiqueAsync(String titre)
    {
        return _iceI_supprimerMusiqueAsync(titre, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> supprimerMusiqueAsync(String titre, java.util.Map<String, String> context)
    {
        return _iceI_supprimerMusiqueAsync(titre, context, false);
    }

    /**
     * @hidden
     * @param iceP_titre -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_supprimerMusiqueAsync(String iceP_titre, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "supprimerMusique", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_titre);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean modifierMusique(String titre, String nouveauTitre, String nouvelAuteur, String nouveauFichierAudio)
    {
        return modifierMusique(titre, nouveauTitre, nouvelAuteur, nouveauFichierAudio, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean modifierMusique(String titre, String nouveauTitre, String nouvelAuteur, String nouveauFichierAudio, java.util.Map<String, String> context)
    {
        return _iceI_modifierMusiqueAsync(titre, nouveauTitre, nouvelAuteur, nouveauFichierAudio, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> modifierMusiqueAsync(String titre, String nouveauTitre, String nouvelAuteur, String nouveauFichierAudio)
    {
        return _iceI_modifierMusiqueAsync(titre, nouveauTitre, nouvelAuteur, nouveauFichierAudio, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> modifierMusiqueAsync(String titre, String nouveauTitre, String nouvelAuteur, String nouveauFichierAudio, java.util.Map<String, String> context)
    {
        return _iceI_modifierMusiqueAsync(titre, nouveauTitre, nouvelAuteur, nouveauFichierAudio, context, false);
    }

    /**
     * @hidden
     * @param iceP_titre -
     * @param iceP_nouveauTitre -
     * @param iceP_nouvelAuteur -
     * @param iceP_nouveauFichierAudio -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_modifierMusiqueAsync(String iceP_titre, String iceP_nouveauTitre, String iceP_nouvelAuteur, String iceP_nouveauFichierAudio, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "modifierMusique", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_titre);
                     ostr.writeString(iceP_nouveauTitre);
                     ostr.writeString(iceP_nouvelAuteur);
                     ostr.writeString(iceP_nouveauFichierAudio);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default void envoyerMusique(String titre, String auteur, String chunk)
    {
        envoyerMusique(titre, auteur, chunk, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void envoyerMusique(String titre, String auteur, String chunk, java.util.Map<String, String> context)
    {
        _iceI_envoyerMusiqueAsync(titre, auteur, chunk, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> envoyerMusiqueAsync(String titre, String auteur, String chunk)
    {
        return _iceI_envoyerMusiqueAsync(titre, auteur, chunk, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> envoyerMusiqueAsync(String titre, String auteur, String chunk, java.util.Map<String, String> context)
    {
        return _iceI_envoyerMusiqueAsync(titre, auteur, chunk, context, false);
    }

    /**
     * @hidden
     * @param iceP_titre -
     * @param iceP_auteur -
     * @param iceP_chunk -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_envoyerMusiqueAsync(String iceP_titre, String iceP_auteur, String iceP_chunk, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "envoyerMusique", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_titre);
                     ostr.writeString(iceP_auteur);
                     ostr.writeString(iceP_chunk);
                 }, null);
        return f;
    }

    default void rechercherParTitre(String titre)
    {
        rechercherParTitre(titre, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void rechercherParTitre(String titre, java.util.Map<String, String> context)
    {
        _iceI_rechercherParTitreAsync(titre, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> rechercherParTitreAsync(String titre)
    {
        return _iceI_rechercherParTitreAsync(titre, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> rechercherParTitreAsync(String titre, java.util.Map<String, String> context)
    {
        return _iceI_rechercherParTitreAsync(titre, context, false);
    }

    /**
     * @hidden
     * @param iceP_titre -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_rechercherParTitreAsync(String iceP_titre, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "rechercherParTitre", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_titre);
                 }, null);
        return f;
    }

    default void rechercherParAuteur(String auteur)
    {
        rechercherParAuteur(auteur, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void rechercherParAuteur(String auteur, java.util.Map<String, String> context)
    {
        _iceI_rechercherParAuteurAsync(auteur, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> rechercherParAuteurAsync(String auteur)
    {
        return _iceI_rechercherParAuteurAsync(auteur, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> rechercherParAuteurAsync(String auteur, java.util.Map<String, String> context)
    {
        return _iceI_rechercherParAuteurAsync(auteur, context, false);
    }

    /**
     * @hidden
     * @param iceP_auteur -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_rechercherParAuteurAsync(String iceP_auteur, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "rechercherParAuteur", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_auteur);
                 }, null);
        return f;
    }

    default boolean play(String titre)
    {
        return play(titre, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean play(String titre, java.util.Map<String, String> context)
    {
        return _iceI_playAsync(titre, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> playAsync(String titre)
    {
        return _iceI_playAsync(titre, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> playAsync(String titre, java.util.Map<String, String> context)
    {
        return _iceI_playAsync(titre, context, false);
    }

    /**
     * @hidden
     * @param iceP_titre -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_playAsync(String iceP_titre, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "play", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_titre);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean stop()
    {
        return stop(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean stop(java.util.Map<String, String> context)
    {
        return _iceI_stopAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> stopAsync()
    {
        return _iceI_stopAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> stopAsync(java.util.Map<String, String> context)
    {
        return _iceI_stopAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_stopAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "stop", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default String[] listerMusiques()
    {
        return listerMusiques(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String[] listerMusiques(java.util.Map<String, String> context)
    {
        return _iceI_listerMusiquesAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<String[]> listerMusiquesAsync()
    {
        return _iceI_listerMusiquesAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<String[]> listerMusiquesAsync(java.util.Map<String, String> context)
    {
        return _iceI_listerMusiquesAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<String[]> _iceI_listerMusiquesAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<String[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "listerMusiques", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String[] ret;
                     ret = istr.readStringSeq();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MusicPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), MusicPrx.class, _MusicPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MusicPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), MusicPrx.class, _MusicPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MusicPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), MusicPrx.class, _MusicPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MusicPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), MusicPrx.class, _MusicPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static MusicPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, MusicPrx.class, _MusicPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static MusicPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, MusicPrx.class, _MusicPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default MusicPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (MusicPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default MusicPrx ice_adapterId(String newAdapterId)
    {
        return (MusicPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default MusicPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (MusicPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default MusicPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (MusicPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default MusicPrx ice_invocationTimeout(int newTimeout)
    {
        return (MusicPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default MusicPrx ice_connectionCached(boolean newCache)
    {
        return (MusicPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default MusicPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (MusicPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default MusicPrx ice_secure(boolean b)
    {
        return (MusicPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default MusicPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (MusicPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default MusicPrx ice_preferSecure(boolean b)
    {
        return (MusicPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default MusicPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (MusicPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default MusicPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (MusicPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default MusicPrx ice_collocationOptimized(boolean b)
    {
        return (MusicPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default MusicPrx ice_twoway()
    {
        return (MusicPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default MusicPrx ice_oneway()
    {
        return (MusicPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default MusicPrx ice_batchOneway()
    {
        return (MusicPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default MusicPrx ice_datagram()
    {
        return (MusicPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default MusicPrx ice_batchDatagram()
    {
        return (MusicPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default MusicPrx ice_compress(boolean co)
    {
        return (MusicPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default MusicPrx ice_timeout(int t)
    {
        return (MusicPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default MusicPrx ice_connectionId(String connectionId)
    {
        return (MusicPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default MusicPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (MusicPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::MusicIce::Music";
    }
}
