//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Music.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.spotifydupauvremobile.ui.MusicIce;

/** @hidden */
public class _MusicPrxI extends com.zeroc.Ice._ObjectPrxI implements MusicPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
